{% set name = "sidecar" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3fa1694b5611c1fab9d7a96c07577ba0764068a89b7b39be9b9ce9770e9d363

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.8.1
    - hatchling
    - jupyter-packaging  >=0.7.9
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.6.0,<9
  run_constrained:
    - jupyterlab >=4,<5

test:
  requires:
    - jupyterlab >=4,<5
    - python {{ python_min }}
  imports:
    - sidecar
  commands:
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyter-widgets/jupyterlab-sidecar/package.json                                      # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyter-widgets\\jupyterlab-sidecar\\package.json (exit 0) else (exit 1)         # [win]
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-sidecar.*OK" labextensions

about:
  home: https://github.com/jupyter-widgets/jupyterlab-sidecar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A sidecar output widget for JupyterLab
  dev_url: https://github.com/jupyter-widgets/jupyterlab-sidecar

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
